"""empty message

Revision ID: 168093130938
Revises: e33dbc8b33c6
Create Date: 2020-04-18 21:33:40.513308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168093130938'
down_revision = 'e33dbc8b33c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(),
                                     nullable=True))  # Added: nullable=True to migrate old records

    # Added: command to update existing records compeleted column to False where they are null.
    op.execute('UPDATE todos SET completed = False WHERE completed is null;')

    # Set column to nullable=False for all future records.
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
